- name: Install python
  homebrew: name=python

- name: Install python3
  homebrew: name=python3

- name: Install ag
  homebrew: name=ag

- name: Install curl
  homebrew: name=curl

- name: Install neomutt
  homebrew: name=neomutt

- name: Install taskwarrior
  homebrew: name=task
