- name: Install stow
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - stow

- name: Install fish
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - fish
