- name: Install neovim
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - neovim

# Deps
- name: Install ripgrep
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - ripgrep

- name: Install g++
  become: true
  become_user: root
  dnf:
    state: present
    name:
      - g++

- name: Install nodejs neovim
  become: true
  become_user: root
  community.general.npm:
    name: neovim
    global: true
